"""Dodano username w Users

Revision ID: 000ac4ccd1e1
Revises: aa62c23c7fa3
Create Date: 2025-02-15 14:08:18.208137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000ac4ccd1e1'
down_revision = 'aa62c23c7fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
