"""stan po dodaniu tabeli Animals

Revision ID: 43c7100c208c
Revises: 694702609ab2
Create Date: 2025-02-18 15:54:05.061906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c7100c208c'
down_revision = '694702609ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('last_edit_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('page_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    # ### end Alembic commands ###
