"""pets edit

Revision ID: 52524044ce98
Revises: 000ac4ccd1e1
Create Date: 2025-02-17 20:35:27.745458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52524044ce98'
down_revision = '000ac4ccd1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('box', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('box')
        batch_op.drop_column('number')
        batch_op.drop_column('weight')
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
