"""add category and in_shelter to animals

Revision ID: 694702609ab2
Revises: b4b9c538b73c
Create Date: 2025-02-18 10:39:33.387248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694702609ab2'
down_revision = 'b4b9c538b73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('in_shelter', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('in_shelter')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
