"""Change pets to animals

Revision ID: b4b9c538b73c
Revises: 52524044ce98
Create Date: 2025-02-17 22:23:51.252773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4b9c538b73c'
down_revision = '52524044ce98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('breed', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.TIMESTAMP(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=6), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('box', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_add', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_off', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['types.type_id'], ),
    sa.PrimaryKeyConstraint('animal_id')
    )
    op.drop_table('pets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('pet_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('breed', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_add', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_off', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('box', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['types.type_id'], name='pets_type_id_fkey'),
    sa.PrimaryKeyConstraint('pet_id', name='pets_pkey')
    )
    op.drop_table('animals')
    # ### end Alembic commands ###
